apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-anwendung
  namespace: mini-projekt
  annotations:
    autor: Felix
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web-anwendung
  template:
    metadata:
      labels:
        app: web-anwendung
      annotations:
        autor: Felix
    spec:
      containers:
      - name: web-anwendung
        image: shade2x/server
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10       
---
apiVersion: v1
kind: Service
metadata:
  name: web-anwendung
  namespace: mini-projekt
spec:
  selector:
    app: web-anwendung
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30080
  type: NodePort